name: auto-commits

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: 签出
        uses: actions/checkout@v3

      - name: 自动化
        run: |
          git config --local user.email "3356136957@qq.com"
          git config --local user.name "AGDDoS-bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Auto-Commits"
          git push
